name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  freeze_windows:
    runs-on: windows-latest
    steps:
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Freeze editor
        run: |
          python build.py freeze
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pywr_editor
          path: dist/main